services:

  catalogdb:
    image: postgres
    
  basketdb:
    image: postgres
    
  distributed-cache:
    image: redis
  
  order-db:
    image: mcr.microsoft.com/mssql/server
  
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
  
  basket.api:
    image: ${DOCKER_REGISTRY-}basket.api
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
  
  discount.grpc:
    image: discount.grpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.GRPC/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:  







