services:

  catalogdb:
    image: postgres
    
  basketdb:
    image: postgres

  distributed-cache:
    image: redis
  
  order-db:
    image: mcr.microsoft.com/mssql/server
    
  message-broker:
    image: rabbitmq:management
  
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
  
  basket.api:
    image: ${DOCKER_REGISTRY-}basket.api
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
  
  discount.grpc:
    image: discount.grpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.GRPC/Dockerfile

  ordering.api:
    image: ordering.api
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
  
  yarpapigateway:
    image: yarpapigateway
    build:
      context: .
      dockerfile: ApiGatways/YarpApiGateway/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:  










